version: '3.3'

services:
    mysql:
        image: mysql:5
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=social-network
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=admin123
            - MYSQL_PORT=3306
        ports:
            - 3306:3306
        volumes:
            - ./mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=admin123
            - PMA_HOST=mysql
        ports:
            - 8080:80
